### ISSUE TITLE
Black text on black background is hard to read for dark mode users

### ISSUE THREAD

**Issue by griffin175** [yaturner/tcamViewerRelease#22]
I'm using a Galaxy S10 (SM-G973U)
Android version 12 - Snow Cone

Display set to dark mode.

![tCamViewer-alpha-dark mode](https://user-images.githubusercontent.com/56269216/222587622-a4815ceb-aaae-4cb0-8a1b-1ba8e81079c0.jpg)

**Comment by yaturner** [comment]
I will investigate this,  the text is white on my device, so this is very
confusing

**Comment by yaturner** [comment]
fixed in 0.3.6
