### ISSUE TITLE
Socket Error, unable to establish a connection. Same tCam-mini works with the app on Windows

### ISSUE THREAD

**Issue by griffin175** [yaturner/tcamViewerRelease#23]
![tCamViewer-alpha-socket-error](https://user-images.githubusercontent.com/56269216/222587976-18107208-d782-410d-b88e-80584ff31d39.jpg)

**Comment by griffin175** [comment]
Hardware: Galaxy S10
OS: Android v12 - Snow Cone

**Comment by yaturner** [comment]
This is a known problem caused by my fat fingers, I will have a new release
that connects properly by this weekend. I am sorry for the inconvience

**Comment by yaturner** [comment]
Fixed in 0.3.3
