### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by IzzySoft** [yaturner/tcamViewerRelease#30]
I see the repo declares the GPL-3.0 license, but I could not find any source code in it – which is a little weird. Did you forget to push it to the repo? Or is it kept in a different one? Thanks for clarification!

**Comment by danjulio** [comment]
Thanks for asking.  The developer released the source code.  You can find it [here](https://github.com/yaturner/tcamViewer-DanJulio).

**Comment by IzzySoft** [comment]
Thanks! Still curious how the two work together. Here, the latest release os a v0.3.6. There, a v1.00 is in the repo tree. I've thought about including the app with [my repo](https://apt.izzysoft.de/fdroid) – but having source code and releases in different repositories makes it difficult, as the updater would look at the source repo. What speaks against having the releases in the source repo, if I might ask?

**Comment by danjulio** [comment]
There were issues and this was the quickest way to get something released after a long delay of no availability.  I know it's not ideal.  Hopefully at some point in the future we can integrate everything into one place and have it all consistently revisioned.

**Comment by IzzySoft** [comment]
OK, I just vaguely remembered I had a comparable case in the past, and just found it: Joplin. So can we apply the same work-around here as well, maybe? In the Readme, at the very start, could you place a hint like "These are the releases for tcamViewer. You can find the source code at https://github.com/yaturner/tcamViewer-DanJulio" (feel free to make it a proper link of course)? Then I could set the "source link" to the releases repo here, and folks could easily follow it. Let me know then where you wish me to link to for issues/bug-reports.
