### ISSUE TITLE
Can't connect on tCam-mini (Android 13)

### ISSUE THREAD

**Issue by CVasilakis** [yaturner/tcamViewerRelease#33]
* Using stock android 13.
* Device: Google Pixel 4A
* Installed v1.0 of the app.
* tCam-mini updated yesterday using the "tcam serial programmer v1.0.0" so it should be running the latest version of its firmware.

The device can connect successfully to the WIFI of the tCam-mini but when i hit the "Connect" button within the app, it will show a "Socket Error" message (image attached). Some times the app crashes (force close) after pressing the "Connect" button.
![image](https://github.com/yaturner/tcamViewerRelease/assets/129665573/5597fa9b-0f49-4302-9458-83c5c7d1234b)
Note: On another device (LG V30) with android 9 the app can connect successfully.

**Comment by danjulio** [comment]
Hey Christopher, we haven't been able to reproduce this.  Are you sure of a couple of things:

1. You put the address 192.168.4.1 in Settings.
2. Nothing else was connected to the tCam-Mini at the same time.

**Comment by CVasilakis** [comment]
The problem disappeared without changing anything to the setup.
It could be a Google Pixel issue.

I'm closing this issue. Thanks for your review.
