### ISSUE TITLE
shared/exported images ignore include metadata setting

### ISSUE THREAD

**Issue by yaturner** [yaturner/tcamViewerRelease#6]

**Comment by danjulio** [comment]
The "include metadata" switch doesn't work like it does for iOS or Desktop.  The intent of turning it off was to send only the image without adornment.  With it turned off, version 0.24 contains a black background, the spotmeter and the palette bar.  I think these should be removed and only the image itself, without the spotmeter drawn over it, sent.

**Comment by yaturner** [comment]
By your command....

**Comment by yaturner** [comment]
fixed
